scrape_configs:
- job_name: "identity-app"
  scrape_interval: 25s 
  static_configs:
  - targets: ["identity.app:80"]
- job_name: "catalog-app"
  scrape_interval: 25s 
  static_configs:
  - targets: ["catalog.app:80"]
  