global:
  scrape_interval: 1s

scrape_configs:
- job_name: "identity-app"
  static_configs:
  - targets: ["identity.app"]
- job_name: "catalog-app"
  static_configs:
  - targets: ["catalog.app"]
  
remote_write:
- url: http://grafana:3000
  basic_auth:
    username: admin
    password: admin