global using Common.Serializers;
global using Catalog.Persistence;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using Polly;
global using Quartz;
global using Common.Domain.Primitives;
global using Common.Domain.Primitives.Events;
global using System.Reflection;
