Serilog:
  Using:
  - "Serilog.Sinks.Console"
  - "Serilog.Sinks.File"
  MinimumLevel:
    Default: "Information"
    Override:
      Microsoft: "Warning"
      System: "Warning"
  WriteTo:
  - Name: "Console"
  - Name: "File"
    Args:
      path: "logs/identityConfigLog-.txt"
      rollingInterval: "Day"

Logging:
  LogLevel:
    Default: "Information"
    Microsoft.AspNetCore: "Warning"

ElasticConfiguration:
  Uri: "http://localhost:9200/"

Jwt:
  RefreshTokenExpirationTimeMinutes: 2000
  TokenExpirationTimeMinutes: 15

Email:
  From: "Eshop"
  Host: "smtp.gmail.com"
  Port: 587
  Username: "akber.sharifov2004@gmail.com"
  Password: "ueey qfia bnyx atce"

AllowedHosts: "*"
