
Serilog: 
  MinimumLevel:
    Default: "Information"
    Override:
      Microsoft: "Warning"
      System: "Warning"

Logging:
  LogLevel:
    Default: "Information"
    Microsoft.AspNetCore: "Warning"

AllowedHosts: "*"