name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies for Catalog app
      run: dotnet restore ./crs/Services/Catalog/Catalog.App/Catalog.App.sln
    - name: Build Catalog app
      run: dotnet build  ./crs/Services/Catalog/Catalog.App/Catalog.App.sln --no-restore
    - name: Unit test Catalog app
      run:  dotnet build ./tests/Catalog.UnitTests/Catalog.UnitTests.csproj --no-restore

    - name: Restore dependencies for Identity app
      run: dotnet restore  ./crs/Services/Catalog/Identity.App/Identity.App.sln
    - name: Build Identity app
      run: dotnet build  ./crs/Services/Identity/Identity.App/Identity.App.sln --no-restore
    - name: Unit test Identity app
      run: dotnet build ./tests/Identity.UnitTests/Identity.UnitTests.csproj --no-restore
