name: Tests

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies 
      run: dotnet restore ./Eshop.sln
      
    - name: Build Identity unit test
      run: dotnet build ./Eshop.sln --configuration Debug
      
    - name: Identity unit test
      run: dotnet test ./Eshop.sln --configuration Debug --logger "trx;LogFileName=test-results.trx" || true
      
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: DotNET Tests
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true
